# FICHIER: _config.yml
# Configuration générale du site
title: Les boucles de Lydie
email: votre_email@exemple.com
description: >-
  Ma collection unique de boucle d'oreilles fait main.
baseurl: "" # Laissez vide si le site est à la racine de Netlify

# Configuration du CMS
collections:
  produits:
    output: true
    permalink: /produits/:path/

# Exclure le dossier du CMS du rendu Jekyll
exclude:
  - admin
