backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "produits"
    label: "Produit"
    folder: "content/produits"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
