backend:
  name: git-gateway
  branch: main # Vérifie que ta branche s'appelle bien main sur GitHub

media_folder: "images" # Les photos seront stockées dans un dossier /images
public_folder: "/images"

collections:
  - name: "produits"
    label: "Mes Produits"
    folder: "content/produits" # Les fichiers textes seront ici
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom du Produit", name: "title", widget: "string"}
      - {label: "Prix (€)", name: "price", widget: "number"}
      - {label: "En Stock ?", name: "available", widget: "boolean", default: true}
      - {label: "Image du Produit", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
